---
apiVersion: "stable.example.com/v1"
kind: CronTab
metadata:
  name: my-new-cron-object
spec:
  cronSpec: "* * * * 5"
  image: my-awesome-cron-image
  minReplicas: {{ .Values.crontab.minReplicas }}
  replicas: {{ .Values.crontab.replicas }}
  maxReplicas: {{ .Values.crontab.maxReplicas }}